"""HeyGen LiveAvatar session tokens for the video consultant.

The avatar is presentation only: sessions are created without a context, so LiveAvatar's own
LLM stays off ("restricted mode") and the avatar only speaks text the frontend sends it
(answers generated by llm_service). The API key never leaves the backend; the browser gets a
short-lived session token and talks to LiveAvatar directly from there.
"""
import httpx
from fastapi import HTTPException, status

from backend.core.config import settings
from backend.services.logger import logger

SANDBOX_MAX_SESSION_SECONDS = 60  # LiveAvatar rejects longer sandbox sessions


def create_session_token() -> dict[str, str]:
    if not settings.liveavatar_api_key:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="Video avatar is not configured")

    persona: dict[str, str] = {"language": "en"}
    if settings.liveavatar_voice_id:
        persona["voice_id"] = settings.liveavatar_voice_id

    payload = {
        "mode": "FULL",
        "avatar_id": settings.liveavatar_avatar_id,
        "is_sandbox": settings.liveavatar_sandbox,
        "avatar_persona": persona,
        # Visitors type (or use our own voice input); the avatar never listens on its own.
        "interactivity_type": "PUSH_TO_TALK",
        "video_settings": {"quality": "medium"},  # 480p keeps streaming latency down
        "max_session_duration": min(settings.liveavatar_max_session_seconds, SANDBOX_MAX_SESSION_SECONDS)
        if settings.liveavatar_sandbox
        else settings.liveavatar_max_session_seconds,
    }

    try:
        response = httpx.post(
            f"{settings.liveavatar_base_url}/v1/sessions/token",
            headers={"X-API-KEY": settings.liveavatar_api_key},
            json=payload,
            timeout=15,
        )
        body = response.json()
        data = body.get("data") or {}
        if response.status_code >= 400 or not data.get("session_token"):
            logger.error(f"LiveAvatar token request failed ({response.status_code}): {str(body)[:300]}")
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="The video consultant is unavailable right now. You can keep chatting by text.",
            )
    except (httpx.HTTPError, ValueError) as exc:
        logger.error(f"LiveAvatar token request failed: {exc}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="The video consultant is unavailable right now. You can keep chatting by text.",
        )

    return {"session_token": data["session_token"], "session_id": data.get("session_id", "")}
